### ISSUE TITLE
Disable analytics for specific browsers

### ISSUE THREAD

**Issue by supermar1010** [ijkml/nuxt-umami#103]
Hello,
According to the docs at umami (https://umami.is/docs/track-events#prevent-tracking-yourself) you should be able to set the key "umami.disabled=1" in local storage  and prevent tracking in that browser. 
As far as I can tell from the source code this is not implemented in nuxt-umami. Is this something you'd feel comfortable adding, I could write a PR for that.
Or is there any other way to disable tracking on a browser basis already? 

Reasoning: It is not about not tracking in development, but excluding mine and some other users page views from distorting the statistics (we only want to track a certain user group)

Thank you for the lib
Mario

**Comment by ijkml** [comment]
Hello, Mario.

Sorry, must have fell through the cracks, great reasoning!
Sure, if it's no bother, shoot the PR, I'd help.
Thanks.

**Comment by supermar1010** [comment]
I'm not 100% sure if this how you'd do it, I can change things up, but I though that was the right spot to do it:)

https://github.com/ijkml/nuxt-umami/pull/105
