### ISSUE TITLE
Add API support

### ISSUE THREAD

**Issue by octo-kumo** [ijkml/nuxt-umami#109]
Hi I was wondering if its possible to have API support. https://umami.is/docs/api/website-stats
Especially if it could be made into slots that we can do something like this.
```vue
<umami-stats pageviews :query="{startAt:0}" v-slot="{data}">
{{page.pageviews.value}} visiters.
</umami-stats>
```

**Comment by ijkml** [comment]
Hello, @octo-kumo 👋.

No. Nuxt Umami only implements the tracker script, other API calls would be outside its scope.

But, this should be possible using Nuxt `$fetch`. And you can even reuse your NU config 😃.

Let me know if you have any questions.
