### ISSUE TITLE
Tracking stopped working !

### ISSUE THREAD

**Issue by ramyahm2010** [ijkml/nuxt-umami#127]
Hello, 

After 11 Dec, all tracking events on my site had been stopped !

kindly, check following image

![image](https://github.com/user-attachments/assets/08bc29e7-f4f7-42a1-9b1f-dcd1a208151d)

I upgraded package to latest version (v3.1.1)

on my localhost i updated package configs as following

```
umami: {
    host: process.env.UMAMI_HOST,
    id: process.env.UMAMI_ID,
    ignoreLocalhost: false,
    logErrors: true,
    autoTrack: true,
  },
```

Now, I get following errors in console !

![image](https://github.com/user-attachments/assets/0ee052fe-971f-467f-8153-757147fda937)

waiting for your kind support & thanks in advance .. Regards,

**Comment by mklueh** [comment]
Same here and I haven't found any breaking changes in their release notes.

It could be that the cloud url has changed to https://cloud.umami.is/api/send

And was previously 

https://analytics.umami.is/api/send

But can't test it right now

**Comment by ramyahm2010** [comment]
Thanks @mklueh 

Updated (host Url) from `https://analytics.eu.umami.is/` to `https://cloud.umami.is/`

and it works fine now.
