### ISSUE TITLE
Add Partytown support

### ISSUE THREAD

**Issue by ijkml** [ijkml/nuxt-umami#14]
While the Umami script is lightweight (about 2kb), the execution might be costly. Adding the script to a production website seemed to significantly affect the lighthouse scores (further testing needed).

Even if this cost is small/average, support for [Partytown](https://github.com/builderio/partytown) would still likely help some.

To implement Partytown, I could either:
- bundle Partytown as a dependency (for all),
- allow specifying whether or not to use Partytown in config (opt-in),
- or... (leave as is).

**Comment by ijkml** [comment]
There is the issue of Partytown working (or not) with injected scripts...

**Comment by vencho-mdp** [comment]
Maybe waiting for `nuxt/scripts` could be an option...

**Comment by ijkml** [comment]
Yes, I'm patiently waiting for that.
