### ISSUE TITLE
Module improvements

### ISSUE THREAD

**Issue by pi0** [ijkml/nuxt-umami#3]
Hi! Following up https://github.com/nuxt/modules/pull/427 i've made a quick review:

- Current [compatibility](https://github.com/ijkml/nuxt-umami/blob/7916cf9dcc1758d578b9364932b050733e1eeb68/src/module.ts#L13) will be broken with latest RC 9+ versions. Please see https://github.com/nuxt/framework/pull/7116
- Plugin is client only, i would suggest to rename it to `plugin.client` and also add a `plugin.server` that mocks `$umami` to avoid breaking users on SSR

Rest seems a nice module 🚀

**Comment by ijkml** [comment]
Hi, thanks for the review. I'll get to work on it, immediately.

Please, to clarify, how do you mean mock? Mock (as in fake) the umami function on the server?

Thank you.

**Comment by pi0** [comment]
An empty function should do the trick. It is to avoid breaking SSR code if someone calls `$umami` wrongly.

**Comment by ijkml** [comment]
Thank you.

Nearly there... Created the mock, and renamed the plugin to `plugin.client`. But now I run into an issue, the module fails to resolve the plugin, unless I change it to 'plugin.client' (which defeats the whole purpose, I'll admit).

Here's the addPlugin function: https://github.com/ijkml/nuxt-umami/blob/012b8cbc22ab3356bd1545fc0d802410079df5bc/src/module.ts#L66

And the error: 
![Error screenshot](https://user-images.githubusercontent.com/52390439/190658079-144bef7e-861f-4ec8-a0e3-5e9c316aa2c2.png)

**Comment by ijkml** [comment]
Hi @pi0 
It seems file name modifiers are not working as expected when using nuxt/kit.

So, what I did was:
- provide the mock as default
- load script (returns `Promise<false>` if window is undefined else `Promise<HTMLScriptElement>`)
    - if false or error, do nothing (ssr)
    - else replace mock with umami

That way umami is mocked if used by mistake, and a warning is logged.

Please let me know what you think, and what other improvements I can make.

**Comment by pi0** [comment]
Hi dear @ijkml. I have checked client-only patch! It is in fact a much nicer solution to use one plugin with ssr fallback. Only as a tip, instead of using `process.env.NODE_ENV !== 'production';`, use `if (process.client)` (inside) the implementation. This way you can hint rollup to **treeshake** client code from server bundle. call to load-script for example can be done like this.

**Comment by ijkml** [comment]
Thank you, @pi0 for your time and patience :pray:

Please have one more look: #5
