### ISSUE TITLE
Nuxt 3 setup

### ISSUE THREAD

**Issue by quentint** [ijkml/nuxt-umami#33]
I tried to configure my Nuxt 3 app to use this module, following the README docs, but couldn't get it to work (the middleware was never called). Also, I could not extend `nuxt-umami@next` (got `Cannot start nuxt:  Cannot find module 'nuxt-umami@next'`) 🤔

Isn't there a more "standard" way of configuring it by adding it to `defineNuxtConfig`'s `modules`?

Here's my config (Nuxt 3):
```js
umami: {
        host: 'https://analytics.umami.is/',
        id: '...',
        version: 2,
    }
```` 

Thanks!

**Comment by ijkml** [comment]
Hi, sorry about that.

Please confirm:
- install `npm i nuxt-umami@next`
- then add to Nuxt `extends: ['nuxt-umami']`
- configure using `app.config.ts` or `appConfig` property

**Comment by ijkml** [comment]
> Isn't there a more "standard" way of configuring it by adding it to `defineNuxtConfig`'s `modules`?

Nuxt Layers is pretty standard, and was more suited to what I had in mind. Long story, I wanted to do a bunch of things that were either not available until Nuxt `v3.3.0` or impossible with Umami v1.

**Comment by quentint** [comment]
Thanks for your help, will try that on Monday and keep you updated. I will also post a reproduction sandbox if needed (should have done that in the first place).

**Comment by ijkml** [comment]
Alright, no problem. Let me know how it goes.
Thank you!

**Comment by quentint** [comment]
A few notes:
- Using `defineNuxtConfig`'s `appConfig` yields `[UMAMI]: `id` is missing or incorrectly configured. Check runtimeConfig.`
- Using `defineAppConfig` in `app.config.ts`' works as expected 😉
