### ISSUE TITLE
Hello World after installing nuxt-umami

### ISSUE THREAD

**Issue by thibaultchazal** [ijkml/nuxt-umami#43]
I'm using nuxt 3.2.3

After installing umami with `npm install nuxt-umami@next`

I added this code to my nuxt.config.ts file
```
export default defineNuxtConfig({
   ...
    extends: ['nuxt-umami'],
    appConfig: {
      umami: {
        autoTrack: true,
        ignoreLocalhost: true,
        domains: 'myProjetURL',
        id: 'myWebsiteFromMyUmamiDashboard',
        host: 'https://theURLofmyUmamiDashboard/',
      }
    }
```

The result is a "Hello World!" blank page instead of my content (no error displayed otherwise).

Am I configuring it wrong?

**Comment by ijkml** [comment]
Hi @thibaultchazal, your config is good :+1:. That's a curious one. Tried restarting your app? Does it show something like this or just hello world?
![Umami playground screenshot](https://user-images.githubusercontent.com/52390439/230141368-a6ab9e95-832c-42b9-973a-d4f0f9b41f96.png)

**Comment by thibaultchazal** [comment]
Hi,

No it's just "Hello World"
![Capture d’écran 2023-04-05 à 19 55 09](https://user-images.githubusercontent.com/6518169/230163756-65cc4e11-5807-40b6-84d5-e9c0e430f581.png)

Sorry I can't give more hints but I have no error neither in the console or the terminal...

**Comment by thibaultchazal** [comment]
Here are my other dependencies
````
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate --dotenv .env.prod",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/image-edge": "^1.0.0-28001428.0aa03b6",
    "@types/markdown-it": "^12.2.3",
    "nuxt": "^3.2.3",
    "nuxt-simple-sitemap": "^2.4.3"
  },
  "dependencies": {
    "markdown-it": "^13.0.1",
    "nuxt-umami": "^2.1.0",
    "sass": "^1.58.3",
    "vuetify": "^3.1.4"
  }
}
````

**Comment by thibaultchazal** [comment]
I also tried to delete both package-lock.json and node_modules then `npm i` but still having "Hello World"

**Comment by thibaultchazal** [comment]
Yes, it is a public repo : https://github.com/Digital-Product-Studio/blog-dps
You'll just wont have the api url but you won't need it.

**Comment by thibaultchazal** [comment]
And it's working as I can see data on my umami dashboard. The only drawback is I can't see my content anymore^^

**Comment by ijkml** [comment]
Hi :wave:, this error happened because of `app.vue` conflicts. Your `app.vue` should override Nuxt Umami's, but since your app didn't have an `app.vue`, well...

That issue is fixed now with [v2.1.3](https://www.npmjs.com/package/nuxt-umami/v/2.1.3).
I hope that helps.

**Comment by thibaultchazal** [comment]
Wonderful ! Thanks a lot @ijkml ;)

**Comment by ijkml** [comment]
Happy to help. 👋
