### ISSUE TITLE
Nuxt Umami is incompatible with Umami (v2) Cloud

### ISSUE THREAD

**Issue by kaboume** [ijkml/nuxt-umami#52]
Hi,
Where can i find the Host value for the Umami Cloud ?
Thanks.

**Comment by ijkml** [comment]
Hi @kaboume 
The host for Umami Cloud is the same as the script URL. You can even copy-paste the full script URL.

**Comment by kaboume** [comment]
Thanks for your reply.
But it doesn't work for me.

nuxt.config.js : 

```
  extends: ['nuxt-umami'],
  appConfig: {
    umami: {
      version: 2,
    },
  },
```

.env : 

```
NUXT_PUBLIC_UMAMI_HOST="https://analytics.umami.is/script.js"
NUXT_PUBLIC_UMAMI_ID="xxx-xx-xx-xx-xxx"
```

I'v tried also with : 
NUXT_PUBLIC_UMAMI_HOST="https://analytics.umami.is/script.js"
or
NUXT_PUBLIC_UMAMI_HOST="https://analytics.umami.is"

But not better.

![analytics](https://user-images.githubusercontent.com/10366465/232251001-4b32bd49-7bf0-458d-ae76-f3dcd2471f1d.png)

**Comment by ijkml** [comment]
Hi @kaboume. Yeah, you're right. I did a little digging and... this lib is no longer compatible with Umami (v2) Cloud.
The error you're getting is not because of the host, the Nuxt Umami is sending data incompatible with the Umami version.

I'll update the Readme to reflect that.

**Comment by kaboume** [comment]
Thanks.
Si what I have to do?

**Comment by ijkml** [comment]
Sorry :pray: 
v1 should work (since it's just a script loader).
https://github.com/ijkml/nuxt-umami/tree/main

**Comment by kaboume** [comment]
@ijkml : it doesn't work any better :(

**Comment by kaboume** [comment]
ah sorry I thought you just had to put 1 instead of 2 in nuxt.config.
In fact, I have to install the previous version...

**Comment by ijkml** [comment]
Oh yeah, :+1: sorry

**Comment by kaboume** [comment]
When should I switch to version 2 of the package so as not to end up with an outdated version 1?

**Comment by ijkml** [comment]
v1 is pretty complete, create an issue if you find a bug or something. v2 is restricted to Umami 1.

I'd have to work on v3 to support Umami 2, but for now, no plans, not until Umami 2 is released and stable.

**Comment by tmlmt** [comment]
Hey @ijkml, what do you mean by Umami 2 being released and stable? It is already in v2.1.0, and the docs should be updated? 

I understand from [here] that it's not only Umami (v2) Cloud you're not compatible with, but also Umami (v2) Open Source (self-hosted). At least that's what my app seems to indicate as, after upgrading to Umami 2.1.0 on my server, nuxt-umami is complaining with a 404 error on not finding `/api/collect`. You may want to adjust slightly your readme to make this even clearer?

**Comment by ijkml** [comment]
As of the time of this issue, Umami 2 was still in beta. Umami v2 or Umami Cloud in this context mean the same thing, sorry if you got that mixed up.

Lots of breaking changes, (see the tracker functions page in the docs), it would require a full rewrite.

So, no, Nuxt Umami v2 doesn't support Umami 2.

**Comment by tmlmt** [comment]
Thanks for your reply. Would be open for a contrib?

**Comment by ijkml** [comment]
Would appreciate that!

**Comment by kaboume** [comment]
thanks for the suggestion but i don't have the technical level to do that :)
