### ISSUE TITLE
Is the new tracker functionnality implemented ?

### ISSUE THREAD

**Issue by Velka-DEV** [ijkml/nuxt-umami#60]
Hi,

As mentioned here: https://umami.is/docs/migrate-v1-v2

`The tracker no longer uses CSS class names to trigger events. It now uses HTML data attributes. See [Track events](https://umami.is/docs/track-events) for more information.`

After testing i noticed that no event is being sent using nuxt-umami ({ version: 2} has been set). So is it on my end or it's not actually implemented in the library ?

Example of usage:

`
        <button
            class="btn btn-sm rounded-full btn-primary mt-4 btn-block"
            data-umami-event="sidebar-button-clicked"
            :data-umami-event-position="head"
            :data-umami-event-tags="Financials, Lifestyle"
            @click="awesome"
        >
            My awesome button
        </button>
`

EDIT: Looking at the library design maybe it's not planned at all ?

**Comment by ijkml** [comment]
Hello @Velka-DEV 

This library aims to be very explicit, so no it doesn't track umami attributes.

It shouldn't be too hard to set up, I think. I hope.
`onMounted()`, get all elements with matching attributes, set up event listeners, and call `umTrackEvent()`.
I could whip up a demo if you need a little help with.

**Comment by ijkml** [comment]
That would be a nice feature, I think. There are interesting ways we could do it, the attributes way, or even a directive.

Sure! Open a PR and we'd work on it.

**Comment by ijkml** [comment]
Closed, #61
