### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by mwinter80** [ijkml/nuxt-umami#63]
Now I ran into another problem using v2 on nuxt3 with the script coming from a free account on umami.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://analytics.umami.is/api/collect. (Reason: CORS request did not succeed). Status code: (null).

My config is given below. In the stackblitz example there was not any security middleware implemented, but is that what I need to do?

Thanks!

appConfig: {
    umami: {
      id: 'xyz',
      host: 'https://analytics.umami.is/'
    },
  }

**Comment by mwinter80** [comment]
I see that this might be a problem because I am testing locally. But that just brings up the question of how I test things. Again, sorry for the noise!

**Comment by ijkml** [comment]
Not a bother...
It seems you forgot to set `version` in the config?

**Comment by mwinter80** [comment]
that did indeed solve the problem. yet another oversight on my part. THANKS!!!!!

**Comment by ijkml** [comment]
It happens, no problem.

But maybe since Umami cloud uses v2, I could make a PR to auto-detect...
