### ISSUE TITLE
Is it possible to disable analytics for a site that is open on the same browser as analytics.umami.is dashboard

### ISSUE THREAD

**Issue by mwinter80** [ijkml/nuxt-umami#70]
I guess the title says it all. I used to run clicky analytics and it somehow did that automagically.

thanks in advance!

**Comment by ijkml** [comment]
Hi @mwinter80, I'm not sure I understand what you're trying to do here. Can you give an example or point me to docs/anything describing that feature of clicky?

Thanks.

**Comment by mwinter80** [comment]
Hi. Sorry if I was unclear. Unfortunately, I cannot find any docs about it and it seems to happen automatically. But here is the scenario explained to the best of my ability.

In the same browser session (firefox), I have my website open and clicky open. Reloading my website does not register a hit on clicky. It is useful because I can check things on my site and navigate through it but not be analyzed as a view. 

Of course, if I open the site in another browser (e.g., chromium), it registers it as a new visitor.

Does that make sense?

Thanks!

-Michael

**Comment by ijkml** [comment]
Hey Michael, I now understand, thanks for the detailed explanation.
Did a quick search and, here it is https://clicky.com/help/faq/tips/different/your-traffic.

> So, Clicky uses cookies...

Clicky sets and tracks unique identifiers, but

- > Umami does not collect any personally identifiable information
- > Umami does not use any cookies

(see https://umami.is/docs/faq). So, no, I don't think this is possible with Umami. Unique identifiers muck up the GDPR waters a bit, but you could try filing a feature request.

On the other hand, using this module, you can achieve something similar, kinda... If you use a service like Netlify or Vercel where you have a subdomain such as `my-app.netlify.app` and your "live" app `my-app.com`, you can set the `domains` option of the module to `['my-app.com']` and that would effectively prevent all analytics on `my-app.netlify.app`.

I know this isn't the same thing as Clicky's, but I hope it helps.

**Comment by mwinter80** [comment]
Thanks for your thoughtful response and suggestions. I guess I just got used to it with clicky, but it is no big deal : )

**Comment by ijkml** [comment]
No problem at all.
Feel free to 🔔 if you hit an issue.
