### ISSUE TITLE
Feature: set id programmatically

### ISSUE THREAD

**Issue by slev-dev** [ijkml/nuxt-umami#77]
We have multiple instances of our site running while each is loading a config file from an external server on pageLoad.
Is it somehow possible to set the umami ID programmatically?

If not, can you point me to the location where i would implement it best? (Maybe via window?)

We are not using SSR btw.

**Comment by ijkml** [comment]
Hi @slev-dev, If you're not using env variables, I think this should be achievable.
Your app's onMounted hook would be a good location, you can use appConfig, like:

```ts
function getWebsiteId() {
  // get stuff
  return 'id...';
}

onMounted(() => {
  useAppConfig().umami.id = getWebsiteId();
});
```

I hope this helps!

**Comment by slev-dev** [comment]
As we disable SSR, env variables do not work.

I did not know that the value of useAppConfig() is writeable - it does the job indeed. Thank you.
