### ISSUE TITLE
No request sended

### ISSUE THREAD

**Issue by Corentin7301** [ijkml/nuxt-umami#9]
Hi!
I would like install Nuwt/Umami on Nuxt 2 but after configure the module according doc:
```
export default {
  modules: [
    'nuxt-umami',
  ],
  umami: {
    autoTrack: true,
    doNotTrack: false,
    websiteId: 'website-id',
    scriptUrl: 'https://analytics.domain.fr/umami.js',
  }
}
```
I don't have any requests in my browser (no script error, no network request), as if nothing was happening...
Sure, in my Umami instance, I haven't datas.

Versions:
`Nuxt version: ^2.15.8`
`nuxt/umami version: ^1.0.2`

Nuxt config:
`ssr: false`
`target: static`

**Comment by ijkml** [comment]
Hi, again @Corentin7301
There was a bunch of problems with Nuxt 2 compatibility.
Should work now with `1.1.0`. Please upgrade, and let me know If you run into any issue.
You can run `npm i nuxt-umami@latest`

**Comment by Corentin7301** [comment]
Hi @ijkml !
I've tested and all is good!
Good job, thank you very much for your fix and your reactivity!

**Comment by ijkml** [comment]
My pleasure 😃
Thanks for discovering that issue 💚.

If it's all good, you can close it.
