### ISSUE TITLE
Does this work with Umami Cloud?

### ISSUE THREAD

**Issue by Gawel91** [ijkml/nuxt-umami#97]
Sorry but I can't get it to work with Umami Cloud with the current documentation.
Is it only for hosted Umami?

**Comment by Gawel91** [comment]
I have this error in my console.
`debug.ts:27 [UMAMI]: `id` is missing or incorrectly configured. Check Umami config. `

Despite my id being there in the nuxt.config.js (I use the Website ID as seen in the Umami dashboard)
```
umami: {
        version: "2",
        id: "xxxx", 
},
```

**Comment by ijkml** [comment]
Can you share a screenshot of your config file, please?

(Blur out or change the id for privacy)

**Comment by Gawel91** [comment]
<img width="793" alt="Screenshot 2024-04-24 at 10 55 32" src="https://github.com/ijkml/nuxt-umami/assets/1862666/5a82c7cf-4aa4-49aa-acb7-09486ceb1f41">
umami has a squiggly red line under it because there is a TypeScript error:
`Object literal may only specify known properties, and 'umami' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.`

**Comment by Gawel91** [comment]
Ahh my bad!

Then I had another error, that the host configuration was missing, so I added `host: "https://us.umami.is"` to the configuration and now it's working! 
Thank you very much for your assistance.
